name: Telegram-connection
version: '1.0'
main: ru.merzko63.telegramconnection.Telegram_connection
description: Telegram integration for Minecraft server
author: merzko63

commands:
  telegram:
    description: Main Telegram plugin command
    aliases: [tg]
    usage: /<command> [test|reload|help]
  tg:
    description: Shortcut for /telegram
    usage: /tg [test|reload|help]
  tgreload:
    description: Reload Telegram plugin config
    usage: /tgreload

permissions:
  telegram.admin:
    description: Allows all Telegram commands
    default: op